// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imitate.proto

package com.fmbah.netty.nio25_28_imitate;

public final class Imitate {
  private Imitate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_imitate_Preq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_imitate_Preq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_imitate_Pres_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_imitate_Pres_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rimitate.proto\022\007imitate\"\023\n\004Preq\022\013\n\003req\030" +
      "\001 \001(\005\"\023\n\004Pres\022\013\n\003res\030\001 \001(\0052\261\001\n\013ImitategR" +
      "pc\022%\n\003p2p\022\r.imitate.Preq\032\r.imitate.Pres\"" +
      "\000\022\'\n\003p2s\022\r.imitate.Preq\032\r.imitate.Pres\"\000" +
      "0\001\022\'\n\003s2p\022\r.imitate.Preq\032\r.imitate.Pres\"" +
      "\000(\001\022)\n\003s2s\022\r.imitate.Preq\032\r.imitate.Pres" +
      "\"\000(\0010\001B-\n com.fmbah.netty.nio25_28_imita" +
      "teB\007ImitateP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_imitate_Preq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_imitate_Preq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_imitate_Preq_descriptor,
        new String[] { "Req", });
    internal_static_imitate_Pres_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_imitate_Pres_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_imitate_Pres_descriptor,
        new String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
