// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imitate.proto

package com.fmbah.netty.nio25_28_imitate;

public interface PreqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imitate.Preq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 req = 1;</code>
   */
  int getReq();
}
