// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imitate.proto

package com.fmbah.netty.nio25_28_imitate;

public interface PresOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imitate.Pres)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 res = 1;</code>
   */
  int getRes();
}
