/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fmbah.netty.大纲.n7.tutorial;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class tutorialConstants {

  public static final int INT32CONSTANT = 9853;

  public static final java.util.Map<String,String> MAPCONSTANT = new java.util.HashMap<String,String>();
  static {
    MAPCONSTANT.put("hello", "world");
    MAPCONSTANT.put("goodnight", "moon");
  }

}
