// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.fmbah.netty.nio24;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fmbah.netty.nio24.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 2;</code>
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
